export const MediaVideoID = 'mediaVideo'
export const ConfirmVideoID = 'confirmVideo'
export const MessageTextAreaID = 'message'
export const PlayInitialVideoButtonID = 'playInitialVideoButton'
export const ShowEBMLButtonID = 'showEBMLButton'
export const PlayVideoWithBigDurationButton = 'playVideoWithBigDurationButton'
export const PlayVideoWithDurationButton = 'playVideoWithDurationButton'
export const PlayVideoWithSheekAndCueButton = 'playVideoWithSheekAndCueButton'
